Fix Some Bugs 1. Clean up redundant info from Zookeeper before setup 2. Fix bug of grafana home page 3. Fix bug of wrong config of prometheus when static mode is used

diff --git a/roles/ecox/tasks/prepare.yml b/roles/ecox/tasks/prepare.yml
--- a/roles/ecox/tasks/prepare.yml
+++ b/roles/ecox/tasks/prepare.yml
@@ -39,6 +39,53 @@
 
 
 #------------------------------------------------------------------------------
+# purge existing postgres
+#------------------------------------------------------------------------------
+# DANGEROUS! remove all postgres data of target machine
+# BUT, this is your choice
+- name: Cleanup postgresql
+  tags: pg_clean
+  become: yes
+  block:
+    - name: Shutdown existing postgres service
+      shell: |
+        # first, gracefully stop service
+        systemctl stop ecox
+        systemctl stop pg_exporter
+
+        # then, manually stop service if still exists
+        if ps -u postgres -o pid:1,command | grep -E 'postmaster|postgres:|-D'  | grep checkpointer ; then
+            pg_ctl -D {{ pg_data }} stop --mode=immediate
+            ps -u postgres -o pid:1,command | grep -E 'postmaster|postgres:|-D' | awk '{print $1}' | xargs kill -9
+        fi
+
+        if ps -u postgres -o pid:1,command | grep -E 'postmaster|postgres:|-D'  | grep checkpointer ; then
+            ps -u postgres -o pid:1,command | grep -E 'postmaster|postgres:|-D' | awk '{print $1}' | xargs kill -9
+            sleep 5 # if still alive, leave 5s grace peroid and force a kill -9
+        fi
+
+        if ps -u postgres -o pid:1,command | grep -E 'postmaster|postgres:|-D'  | grep checkpointer ; then
+            exit 1  # report failure if still alive
+        fi
+        exit 0
+
+
+    - name: Remove registerd zookeeper service
+      ignore_errors: yes
+      shell: |
+        export LD_LIBRARY_PATH=/usr/EcoX/lib
+        /usr/EcoX/bin/zkcli {{ zkhost }} deleteall {{ pg_cluster }}
+        exit 0
+
+
+    # TODO: only remove necessary dir instead of all
+    - name: Remove existing postgres data
+      file: path={{ item }} state=absent
+      with_items:
+        - /pg
+
+
+#------------------------------------------------------------------------------
 # Create Directory
 #------------------------------------------------------------------------------
 # this assumes that
@@ -96,6 +143,7 @@
 
     - name: Make sure data dir exists
       file: path={{ pg_data }} state=directory owner={{ pg_dbsu }} mode=0700
+
 
 
 #------------------------------------------------------------------------------
